import * as dotenv from "dotenv";
dotenv.config();

export const config = {
  zerodha: {
    apiKey: process.env.ZERODHA_API_KEY || "",
    accessToken: process.env.ZERODHA_ACCESS_TOKEN || "",
  },
  openai: { apiKey: process.env.OPENAI_API_KEY || "" },
  capital: parseInt(process.env.CAPITAL || "100000"),
  riskPercent: parseFloat(process.env.RISK_PERCENT || "0.02"),
  maxSignals: parseInt(process.env.MAX_SIGNALS || "20"),
  runIntervalMinutes: parseInt(process.env.RUN_INTERVAL_MINUTES || "15"),
};

export const SECTOR_SYMBOLS: Record<string, string[]> = {
  // ─── Banking & Finance ─────────────────────────────────────────────────────
  "Banking & Finance": [
    // Large-cap private banks
    "HDFCBANK",
    "ICICIBANK",
    "AXISBANK",
    "KOTAKBANK",
    "INDUSINDBK",
    "FEDERALBNK",
    "KARNATAKBANK",
    "CSBBANK",
    "DCBBANK",
    "RBLBANK",
    "YESBANK",
    "IDFCFIRSTB",
    "BANDHANBNK",
    "UJJIVANSFB",
    "EQUITASBNK",
    // PSU banks
    "SBIN",
    "BANKBARODA",
    "PNB",
    "CANBK",
    "UNIONBANK",
    "INDIANB",
    "IOB",
    "UCOBANK",
    "MAHABANK",
    "J&KBANK",
    // NBFCs
    "BAJFINANCE",
    "BAJAJFINSV",
    "CHOLAFIN",
    "MUTHOOTFIN",
    "MANAPPURAM",
    "M&MFIN",
    "LTFH",
    "HDFCAMC",
    "IIFL",
    "MOTILALOFS",
    "ANGELONE",
    "5PAISA",
    "ICICIPRULI",
    "HDFCLIFE",
    "SBILIFE",
    "LICI",
    "STARHEALTH",
    "ABCAPITAL",
    "POONAWALLA",
    "SBICARD",
  ],

  // ─── IT & Technology ───────────────────────────────────────────────────────
  "IT & Technology": [
    // Large-cap IT
    "TCS",
    "INFY",
    "WIPRO",
    "HCLTECH",
    "TECHM",
    "LTI",
    "LTIM",
    "PERSISTENT",
    "COFORGE",
    "MPHASIS",
    "LTTS",
    "TATAELXSI",
    "NIIT",
    "MASTEK",
    "HEXAWARE",
    "KPITTECH",
    "RATEGAIN",
    "ROUTE",
    "TANLA",
    "INTELLECT",
    // Internet / SaaS / Fintech
    "NAUKRI",
    "INDIAMART",
    "ZOMATO",
    "POLICYBZR",
    "DELHIVERY",
    "PAYTM",
    "CARTRADE",
    "MAPMYINDIA",
    "NAZARA",
    "HAPPIEST",
    "NEWGEN",
    "SAKSOFT",
    "DATAMATICS",
    "SONATSOFTW",
    "CYIENT",
    "BIRLASOFT",
    "ECLERCX",
    "ZENSAR",
    "FSL",
    "INFIBEAM",
  ],

  // ─── Pharma & Healthcare ───────────────────────────────────────────────────
  "Pharma & Healthcare": [
    // Large-cap pharma
    "SUNPHARMA",
    "DRREDDY",
    "CIPLA",
    "DIVISLAB",
    "LUPIN",
    "AUROPHARMA",
    "TORNTPHARM",
    "ALKEM",
    "NATCOPHARM",
    "IPCALAB",
    "GLENMARK",
    "GRANULES",
    "JBCHEPHARM",
    "PFIZER",
    "ABBOTINDIA",
    "GLAXO",
    "SANOFI",
    "BIOCON",
    "LAURUS",
    "ERIS",
    // Hospitals & diagnostics
    "APOLLOHOSP",
    "FORTIS",
    "MAXHEALTH",
    "MEDANTA",
    "ASTER",
    "THYROCARE",
    "METROPOLIS",
    "POLYMED",
    "VIJAYA",
    "MEDPLUS",
    "KRSNAA",
    "SUVENPHAR",
    "STRIDES",
    "BLISSGVS",
    "CAPLIPOINT",
  ],

  // ─── Auto & EV ─────────────────────────────────────────────────────────────
  "Auto & EV": [
    // OEMs
    "MARUTI",
    "TATAMOTORS",
    "M&M",
    "BAJAJ-AUTO",
    "HEROMOTOCO",
    "TVSMOTORS",
    "EICHERMOT",
    "ASHOKLEY",
    "FORCEMOT",
    "ESCORTS",
    "OLECTRA",
    "GREENPANEL",
    "TIINDIA",
    "CRAFTSMAN",
    "SUPRAJIT",
    // Auto ancillaries
    "MOTHERSON",
    "BALKRISIND",
    "BOSCHLTD",
    "BHARATFORG",
    "EXIDEIND",
    "AMARAJABAT",
    "SUNDRMFAST",
    "GABRIEL",
    "SUBROS",
    "ENDURANCE",
    "MINDARIND",
    "LUMAX",
    "FIEM",
    "MINDA",
    "SSWL",
    // EV / charging
    "TATAPOWER",
    "OLECTRA",
    "GREENZO",
  ],

  // ─── Energy & Power ────────────────────────────────────────────────────────
  "Energy & Power": [
    // Oil & gas
    "RELIANCE",
    "ONGC",
    "BPCL",
    "IOC",
    "HINDPETRO",
    "CASTROLIND",
    "MRPL",
    "CHENNPETRO",
    "GAIL",
    "PETRONET",
    "IGL",
    "MGL",
    "GSPL",
    "GUJGASLTD",
    "ATGL",
    // Power generation & T&D
    "NTPC",
    "POWERGRID",
    "ADANIGREEN",
    "ADANITRANS",
    "TATAPOWER",
    "CESC",
    "TORNTPOWER",
    "JSPL",
    "NHPC",
    "SJVN",
    "RPOWER",
    "JSWENERGY",
    "GREENPANEL",
    "INOXWIND",
    "SUZLON",
    "ORIENTGREEN",
    "WEBSOL",
    "WAAREEENER",
    "PREMIER",
    "KPI",
  ],

  // ─── Capital Goods & Defence ───────────────────────────────────────────────
  "Capital Goods & Defence": [
    "LT",
    "BHEL",
    "HAL",
    "BEL",
    "COCHINSHIP",
    "MAZAGON",
    "GRINDWELL",
    "THERMAX",
    "CUMMINSIND",
    "ABB",
    "SIEMENS",
    "HONAUT",
    "VOLTAMP",
    "ELGIEQUIP",
    "KIRLOSENG",
    "KNRCON",
    "PNCINFRA",
    "GMRINFRA",
    "IRB",
    "KEC",
    "KALPATPOWR",
    "SGEL",
    "TRITURBINE",
    "DYNAMATECH",
    "DATPATTERN",
    "ASTRAZEN",
    "PARAS",
    "ZEN",
    "MTAR",
    "IDEAFORGE",
  ],

  // ─── Consumer & FMCG ──────────────────────────────────────────────────────
  "Consumer & FMCG": [
    "HINDUNILVR",
    "ITC",
    "NESTLEIND",
    "BRITANNIA",
    "DABUR",
    "MARICO",
    "TATACONSUM",
    "COLPAL",
    "GODREJCP",
    "EMAMILTD",
    "PGHH",
    "VBLLTD",
    "RADICO",
    "UNITEDBREWS",
    "UNITEDSPIRITS",
    "MCDOWELL-N",
    "JYOTHYLAB",
    "BAJAJCON",
    "ZYDUSWELL",
    "KANSAINER",
    "BERGER",
    "ASIANPAINT",
    "AKZOINDIA",
    "SHALPAINTS",
    "INDIGO",
    "AVANTIFEED",
    "APEX",
    "BIKAJI",
    "DOMS",
    "WONDERLA",
  ],

  // ─── Real Estate ───────────────────────────────────────────────────────────
  "Real Estate": [
    "DLF",
    "GODREJPROP",
    "OBEROIRLTY",
    "PRESTIGE",
    "BRIGADE",
    "SOBHA",
    "PHOENIXLTD",
    "MAHINDCIE",
    "INDHOUSING",
    "SUNTECK",
    "KOLTEPATIL",
    "PURVA",
    "RUSTOMJEE",
    "ANANTRAJ",
    "GANESHHOUC",
    "LODHA",
    "MACROTECH",
    "SIGNATURE",
    "AARTECH",
    "NSLNISP",
  ],

  // ─── Metals & Mining ──────────────────────────────────────────────────────
  "Metals & Mining": [
    // Steel
    "TATASTEEL",
    "JSWSTEEL",
    "SAIL",
    "JINDALSAW",
    "RATNAMANI",
    "APLAPOLLO",
    "MSTEEL",
    "KALYANKJIL",
    "GALLISPAT",
    "WELCORP",
    // Aluminium / zinc / copper
    "HINDALCO",
    "VEDL",
    "NALCO",
    "HINDZINC",
    "NMDC",
    "COALINDIA",
    "MOIL",
    "GMDC",
    "KIOCL",
    "SANDUMA",
    // Specialty metals
    "MIDHANI",
    "TINPLATE",
    "STEELHCL",
    "SHYAMMETL",
    "JSPL",
  ],

  // ─── Chemicals & Specialty ─────────────────────────────────────────────────
  "Chemicals & Specialty": [
    "PIDILITIND",
    "SRF",
    "DEEPAKNITRITE",
    "NAVINFLUOR",
    "ATUL",
    "VINATI",
    "NOCIL",
    "CLEAN",
    "FINEORG",
    "SUDARSCHEM",
    "TATACHEM",
    "GNFC",
    "COROMANDEL",
    "CHAMBAL",
    "GSFC",
    "AAVAS",
    "ASTRAL",
    "GALAXYSURF",
    "ARCHCHEM",
    "ROSSELLIND",
    "LXCHEM",
    "DMCC",
    "TATACHEM",
    "IGPL",
    "BALCHEM",
    "PCBL",
    "INOXAP",
    "KIRI",
    "BORAXMORAR",
    "EPIGRAL",
  ],

  // ─── Infrastructure & Cement ───────────────────────────────────────────────
  "Infrastructure & Cement": [
    // Cement
    "ULTRACEMCO",
    "GRASIM",
    "AMBUJACEM",
    "ACC",
    "JKCEMENT",
    "SHREECEM",
    "RAMCOCEM",
    "HEIDELBERG",
    "BIRLACORPN",
    "DALMIA",
    "NUVOCO",
    "PRISMJOINTS",
    "ORIENTCEM",
    "STARCEMENT",
    "JKLAKSHMI",
    // Infrastructure / construction
    "KNRCON",
    "PNCINFRA",
    "GPPL",
    "IRFC",
    "NCC",
    "HGINFRA",
    "DBCORP",
    "GMRINFRA",
    "IRB",
    "ASHOKA",
    "WELSPUNIND",
    "CAPACITE",
    "PSP",
    "PDSL",
    "AHLUCONT",
  ],

  // ─── Retail & Consumption ─────────────────────────────────────────────────
  "Retail & Consumption": [
    "DMART",
    "TRENT",
    "TITAN",
    "NYKAA",
    "ZOMATO",
    "JUBLFOOD",
    "DEVYANI",
    "WESTLIFE",
    "BATA",
    "RAYMOND",
    "VMART",
    "SHOPERSTOP",
    "ABFRL",
    "PAGEIND",
    "MANYAVAR",
    "CAMPUS",
    "METRO",
    "SAPPHIRE",
    "BARBEQUE",
    "EASEMYTRIP",
    "IRCTC",
    "INDIGOPNTS",
    "IXIGO",
    "YATHARTH",
    "SENCO",
  ],

  // ─── Telecom & Media ──────────────────────────────────────────────────────
  "Telecom & Media": [
    "BHARTIARTL",
    "IDEA",
    "TATACOMM",
    "HATHWAY",
    "GTPL",
    "SUNTV",
    "ZEEL",
    "PVRINOX",
    "SAREGAMA",
    "TIPS",
    "INOXLEISURE",
    "NETWORKI8",
    "TVTODAY",
    "DBCORP",
    "JAGRAN",
    "DISH",
    "APTUS",
    "DEN",
    "HINDMEDIA",
    "MIDCAP",
  ],

  // ─── Insurance & Asset Management ─────────────────────────────────────────
  "Insurance & Asset Mgmt": [
    "HDFCLIFE",
    "SBILIFE",
    "ICICIPRULI",
    "LICI",
    "STARHEALTH",
    "ABCAPITAL",
    "MUTHOOTFIN",
    "MANAPPURAM",
    "IIFL",
    "MOTILALOFS",
    "ANGELONE",
    "NUVAMA",
    "EDELWEISS",
    "GEOJITFSL",
    "ISEC",
    "CAMS",
    "CDSL",
    "BSE",
    "MCX",
    "NSEINDIA",
  ],

  // ─── Logistics & Supply Chain ─────────────────────────────────────────────
  "Logistics & Supply Chain": [
    "DELHIVERY",
    "BLUEDART",
    "GATI",
    "TCI",
    "MAHINDLOG",
    "CONCOR",
    "VRL",
    "ALLCARGO",
    "AEGISLOG",
    "WABCOINDIA",
    "SICAL",
    "SNOWMAN",
    "GATEWAY",
    "ESAB",
    "OCCL",
  ],

  // ─── Agri & Food Processing ────────────────────────────────────────────────
  "Agri & Food Processing": [
    "UPL",
    "PIIND",
    "BAYER",
    "RALLIS",
    "DHANUKA",
    "INSECTICID",
    "HERANBA",
    "GODREJAGRO",
    "KSBL",
    "SUMITCHEM",
    "KRBL",
    "LT FOODS",
    "PATANJALI",
    "AVANTIFEED",
    "APEX",
    "BIKAJI",
    "AGROPHOS",
    "GLOBUS",
    "USHAMART",
    "ZYDUSLIFE",
  ],

  // ─── Textiles & Apparel ────────────────────────────────────────────────────
  "Textiles & Apparel": [
    "RAYMOND",
    "WELSPUNIND",
    "VARDHMAN",
    "TRIDENT",
    "GRASIM",
    "PAGEIND",
    "ABFRL",
    "MANYAVAR",
    "TRENTLTD",
    "NITIN",
    "KITEX",
    "FILATEX",
    "NAHARSPG",
    "SPANDANA",
    "RUPA",
    "LAXMIMACH",
    "NILAINFO",
    "SHIVALIK",
    "SPORTKING",
    "SUTLEJ",
  ],

  // ─── Paints & Building Materials ──────────────────────────────────────────
  "Paints & Building Materials": [
    "ASIANPAINT",
    "BERGER",
    "KANSAINER",
    "AKZOINDIA",
    "SHALPAINTS",
    "INDIGO",
    "SUPREMEIND",
    "ASTRAL",
    "CERA",
    "SOMANY",
    "KAJARIA",
    "ORIFLAME",
    "GRINDWELL",
    "GREENPANEL",
    "GREENPLY",
    "CENTURYPLY",
    "HSIL",
    "VINYLINDIA",
    "RUSHIL",
    "STYLAM",
  ],

  // ─── Diversified Conglomerates ─────────────────────────────────────────────
  "Diversified Conglomerates": [
    "RELIANCE",
    "TATAMOTORS",
    "M&M",
    "ADANIENT",
    "ADANITRANS",
    "LT",
    "ITC",
    "BAJAJHIND",
    "GRASIM",
    "HINDALCO",
    "MCDOWELL-N",
    "GODREJCP",
    "TATACONSUM",
    "TATACOMM",
    "BIRLASOFT",
  ],

  // ─── Small & Micro Cap Multibaggers ────────────────────────────────────────
  "Small & Micro Cap": [
    "DATPATTERN",
    "MTAR",
    "IDEAFORGE",
    "SBFC",
    "GANDHAR",
    "SENCO",
    "YATHARTH",
    "IXIGO",
    "APTUS",
    "FIVESTAR",
    "HOMEFIRST",
    "CREDITACC",
    "SPANDANA",
    "ARMANFIN",
    "UGROCAP",
    "SANSERA",
    "CRAFTSMAN",
    "KAYNES",
    "AVALON",
    "ELIN",
    "SYRMA",
    "UTKARSH",
    "SURYODAY",
    "JANA",
    "NSLNISP",
    "SIGACHI",
    "DIVGI",
    "BIRLACABLE",
    "ASAHIINDIA",
    "SBCL",
    "JYOTICNC",
    "ANUPAM",
    "TATAINVEST",
    "TIPSINDLTD",
    "GALLANTT",
    "URJA",
    "TATVA",
    "VAIBHAVGBL",
    "ORIENTBELL",
    "GESHIP",
    "BALRAMCHIN",
    "KSCL",
    "JTEKTINDIA",
    "EPIGRAL",
    "RATEGAIN",
  ],
};
